[project]
name = "parroting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.11.0",
    "chronos>=0.3",
    "datasets>=4.4.1",
    "dysts>=0.95",
    "einops>=0.8.1",
    "gluonts[arrow]>=0.16.2",
    "huggingface-hub>=0.36.0",
    "ipykernel>=7.1.0",
    "ipython>=9.7.0",
    "jax>=0.8.0",
    "jaxtyping>=0.3.3",
    "jupyter>=1.1.1",
    "lightning>=2.5.6",
    "matplotlib>=3.10.7",
    "numba>=0.62.1",
    "numpy<2.2",
    "omegaconf>=2.3.0",
    "pmdarima>=2.1.1",
    "safetensors>=0.6.2",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.3",
    "sktime>=0.39.0",
    "statsmodels>=0.14.5",
    "torch>=2.9.1",
    "transformers>=4.56.0",
]

[tool.uv.sources]
dysts = { git = "https://github.com/GilpinLab/dysts" }
